// lib/countries.ts
export const countries = [
    { code: "US", label: "United States", flag: "https://flagcdn.com/us.svg", dialCode: "+1", export: "Technology, Aerospace, Machinery, Agricultural Products" },
    { code: "CA", label: "Canada", flag: "https://flagcdn.com/ca.svg", dialCode: "+1", export: "Oil, Vehicles, Machinery, Agricultural Products" },
    { code: "GB", label: "United Kingdom", flag: "https://flagcdn.com/gb.svg", dialCode: "+44", export: "Machinery, Vehicles, Pharmaceuticals, Oil" },
    { code: "DE", label: "Germany", flag: "https://flagcdn.com/de.svg", dialCode: "+49", export: "Vehicles, Machinery, Chemicals, Electronics" },
    { code: "CN", label: "China", flag: "https://flagcdn.com/cn.svg", dialCode: "+86", export: "Electronics, Machinery, Textiles, Steel" },
    { code: "JP", label: "Japan", flag: "https://flagcdn.com/jp.svg", dialCode: "+81", export: "Vehicles, Machinery, Electronics, Chemicals" },
    { code: "FR", label: "France", flag: "https://flagcdn.com/fr.svg", dialCode: "+33", export: "Aircraft, Machinery, Chemicals, Wine" },
    { code: "IN", label: "India", flag: "https://flagcdn.com/in.svg", dialCode: "+91", export: "Petroleum Products, Gems, Pharmaceuticals, Textiles" },
    { code: "IT", label: "Italy", flag: "https://flagcdn.com/it.svg", dialCode: "+39", export: "Machinery, Vehicles, Chemicals, Fashion" },
    { code: "BR", label: "Brazil", flag: "https://flagcdn.com/br.svg", dialCode: "+55", export: "Soybeans, Coffee, Iron Ore, Vehicles" },
    { code: "AU", label: "Australia", flag: "https://flagcdn.com/au.svg", dialCode: "+61", export: "Minerals, Coal, Natural Gas, Gold" },
    { code: "RU", label: "Russia", flag: "https://flagcdn.com/ru.svg", dialCode: "+7", export: "Oil, Natural Gas, Coal, Metals" },
    { code: "MX", label: "Mexico", flag: "https://flagcdn.com/mx.svg", dialCode: "+52", export: "Vehicles, Machinery, Oil, Electrical Machinery" },
    { code: "KR", label: "South Korea", flag: "https://flagcdn.com/kr.svg", dialCode: "+82", export: "Semiconductors, Cars, Ships, Electronics" },
    { code: "SG", label: "Singapore", flag: "https://flagcdn.com/sg.svg", dialCode: "+65", export: "Electronics, Machinery, Chemicals, Petroleum Products" },
    { code: "ZA", label: "South Africa", flag: "https://flagcdn.com/za.svg", dialCode: "+27", export: "Minerals, Gold, Diamonds, Vehicles" },
    { code: "NL", label: "Netherlands", flag: "https://flagcdn.com/nl.svg", dialCode: "+31", export: "Machinery, Electronics, Chemicals, Flowers" },
    { code: "SE", label: "Sweden", flag: "https://flagcdn.com/se.svg", dialCode: "+46", export: "Machinery, Vehicles, Iron and Steel, Paper" },
    { code: "CH", label: "Switzerland", flag: "https://flagcdn.com/ch.svg", dialCode: "+41", export: "Pharmaceuticals, Machinery, Chemicals, Watches" },
    { code: "AE", label: "United Arab Emirates", flag: "https://flagcdn.com/ae.svg", dialCode: "+971", export: "Oil, Gold, Jewelry, Chemicals" },
    { code: "TR", label: "Turkey", flag: "https://flagcdn.com/tr.svg", dialCode: "+90", export: "Textiles, Machinery, Vehicles, Electronics" },
    { code: "ID", label: "Indonesia", flag: "https://flagcdn.com/id.svg", dialCode: "+62", export: "Palm Oil, Coal, Electrical Machinery, Rubber" },
    { code: "MY", label: "Malaysia", flag: "https://flagcdn.com/my.svg", dialCode: "+60", export: "Electronics, Petroleum Products, Palm Oil, Machinery" },
    { code: "IR", label: "Iran", flag: "https://flagcdn.com/ir.svg", dialCode: "+98", export: "Oil, Petrochemicals, Natural Gas, Minerals" },
    { code: "SA", label: "Saudi Arabia", flag: "https://flagcdn.com/sa.svg", dialCode: "+966", export: "Oil, Petrochemicals, Plastics, Chemicals" },
    { code: "EG", label: "Egypt", flag: "https://flagcdn.com/eg.svg", dialCode: "+20", export: "Petroleum, Chemicals, Textiles, Agricultural Products" },
    { code: "AE", label: "United Arab Emirates", flag: "https://flagcdn.com/ae.svg", dialCode: "+971", export: "Oil, Gold, Jewelry, Chemicals" },
    { code: "KW", label: "Kuwait", flag: "https://flagcdn.com/kw.svg", dialCode: "+965", export: "Oil, Petrochemicals, Plastics" },
    { code: "QA", label: "Qatar", flag: "https://flagcdn.com/qa.svg", dialCode: "+974", export: "Natural Gas, Petroleum, Petrochemicals" },
    { code: "OM", label: "Oman", flag: "https://flagcdn.com/om.svg", dialCode: "+968", export: "Oil, Gas, Chemicals, Textiles" },
    { code: "LB", label: "Lebanon", flag: "https://flagcdn.com/lb.svg", dialCode: "+961", export: "Petroleum Products, Jewelry, Machinery, Textiles" },
    { code: "JO", label: "Jordan", flag: "https://flagcdn.com/jo.svg", dialCode: "+962", export: "Phosphates, Potash, Textiles, Chemicals" },
    { code: "DZ", label: "Algeria", flag: "https://flagcdn.com/dz.svg", dialCode: "+213", export: "Natural Gas, Petroleum, Chemicals, Agricultural Products" },
    { code: "MA", label: "Morocco", flag: "https://flagcdn.com/ma.svg", dialCode: "+212", export: "Phosphates, Textiles, Machinery, Agricultural Products" },
    { code: "TN", label: "Tunisia", flag: "https://flagcdn.com/tn.svg", dialCode: "+216", export: "Textiles, Petroleum, Chemicals, Machinery" }
];
