// file generated by the Paraglide-Next init command
import { middleware as paraglide } from "@/lib/i18n"
import type { NextRequest } from "next/server"
import { middleware as i18nMiddleware } from "@/lib/i18n"

export async function middleware(request: any) {
	const lang = i18nMiddleware.detectLanguage(request)
	const response = i18nMiddleware.getResponse(request, lang)
	return response
}
export const config = {
	matcher: [
		/*
		 * Match all request paths except for the ones starting with:
		 * - api (API routes)
		 * - _next/static (static files)
		 * - _next/image (image optimization files)
		 * - favicon.ico (favicon file)
		 */
		"/((?!api|_next/static|_next/image|favicon.ico).*)",
	],
}
